### ISSUE TITLE
Can you consider allowing users to add connection headers. 

### ISSUE THREAD

**Issue by osiloke** [tus/tus-java-client#2]
This will allow authorization headers. I know authorization is not part of the protocol, but the protocol documentation suggest that you should perform authorization via additional headers. The current api does not allow this.

**Comment by Acconut** [comment]
Sure, this should be a relatively easy fix. Do you speak about headers per client (`TusClient#setHeaders`), per upload (`TusUpload#setHeaders`) or both in your case? Since I see use cases for all situations, I guess we need both.

**Comment by osiloke** [comment]
so i think both cases are helpful at least for flexibility.

**Comment by Acconut** [comment]
Currently sitting on implementing this feature. Expect it soon!

**Comment by Acconut** [comment]
The `0.3.0` release includes this feature.
