### ISSUE TITLE
io.tus.java.client.ProtocolException: unexpected status code (413) while uploading chunk

### ISSUE THREAD

**Issue by hvk-android** [tus/tus-java-client#21]
This Exception occurs when uploading finished in  "uploader.finish()". also some times **EPIPE Broken** error occurs.
[f.txt](https://github.com/tus/tus-java-client/files/1960331/f.txt)

**Comment by hvk-android** [comment]
We are using tus GO server in Digital Ocean.
https://github.com/tus/tusd
Also when i upload small file it works fine but for large file   **EPIPE Broken Pipe** error occurs.
![device-2018-05-01-092831](https://user-images.githubusercontent.com/38374762/39460580-1eb3df9a-4d22-11e8-96dc-ddcb311c3ada.png)

**Comment by Acconut** [comment]
Firstly, are you using a proxy in front of nginx which could respond with the 413 error?

Secondly, what exactly are you doing when the 413 errors occur? What file sizes work, which don't? Please share more details or we can't help you.

Finally, when working on the network, errors are not always preventable but sometimes we just have to retry. tus-java-client has excellent support for retries using the `TusExecutor` class. Please see the example (https://github.com/tus/tus-java-client#usage) for more details.
