### ISSUE TITLE
Ability to cancel an ongoing upload?

### ISSUE THREAD

**Issue by rameeznkhan** [tus/tus-java-client#24]
Once i start upload for any file I can't cancel/abort it. How can I do that?

**Comment by Acconut** [comment]
What do you exactly mean with "cancel/abort"? Please be more precise about what situation you are describing. However, I can say two things:

* If you want to stop an upload, just stop calling the `TusUploader#uploadChunk()` method and close all requests using `TusUploader#finish()`.
* A call to `TusUploader#uploadChunk()` cannot be interrupted and you will have to wait until it is finished. Setting a smaller chunk size helps reduce the wait time.

**Comment by rameeznkhan** [comment]
I mean I don't want to upload the file anymore. Thank you though reducing the chunk size helps me get callbacks faster.

**Comment by Acconut** [comment]
> I mean I don't want to upload the file anymore. 

Ok, in that case not calling the `TusUploader#uploadChunk() ` method and closing all requests using `TusUploader#finish()` should be enough.

> Thank you though reducing the chunk size helps me get callbacks faster.

You're welcome :)
