### ISSUE TITLE
Sending IPCamera frames

### ISSUE THREAD

**Issue by EhsanVahab** [tus/tus-java-client#25]
Hi friends,
I'm actually new at working with TUS protocol.
I'm just wondering it's possible to send IP camera frames with TUS?

**Comment by Acconut** [comment]
Yes, you can send any data using the tus protocol. In theory you could push the raw frame data but I would recommend you to encode it first to save bandwidth etc.

**Comment by EhsanVahab** [comment]
Dear @Acconut ,
Thanks for your answer.
I'v been looking into the documentation sand your blog's post, and found that streaming has been recently added into your great protocol. However I couldn't find any sample code written by Java or any other language. 
Actually I'm going to stream my IP Camera's frame to a TUS server and store them as a video file.
could you direct me into a right page or give me some documentation about?

**Comment by Acconut** [comment]
> I'v been looking into the documentation and your blog's post, and found that streaming has been recently added into your great protocol.

You are likely referring to the upload-length-deferring feature (see https://tus.io/protocols/resumable-upload.html#creation), aren't you? Using this feature the client isn't required to specify a file size when creating an upload and can just start to upload a continuous data stream.

> However I couldn't find any sample code written by Java or any other language.

The tus-java-client currently doesn't have this feature implemented but it shouldn't be too hard to add it if you want to give it a try. We are always happy to assist you!

On the other hand, tus-js-client has it already implemented (see the uploadLengthDeferred option at https://github.com/tus/tus-js-client/#tusdefaultoptions) and it ships with an example for streaming video from the browser: https://github.com/tus/tus-js-client/blob/master/demos/browser/video.js

Let me know if that helps you or if you want to give the implementation a shot!

**Comment by EhsanVahab** [comment]
Dear @Acconut ,
I deeply appreciate you for your great answer.
I've got what I want. I'm trying to send my Ip Camera's frames to a computer and store them as a video file.

**Comment by Acconut** [comment]
Ok, glad to read I was able to help you. :)
