### ISSUE TITLE
Errors resuming should automatically create

### ISSUE THREAD

**Issue by cjhenck** [tus/tus-java-client#3]
If a server has lost track of a started upload (e.g. sends back a 404), should the client default to creating a new one instead of failing or throwing the exception?

**Comment by Acconut** [comment]
Yes, you are absolutely right in this question and there is already work done for achieving this in the `retrying-client` branch.

**Comment by Acconut** [comment]
I finally came around to fix this. I apologize for waiting so long. This will land in the next release soon.

**Comment by Acconut** [comment]
Release 0.3.1 which contains this patch is on it's way to the registry.
