### ISSUE TITLE
(411) while creating upload

### ISSUE THREAD

**Issue by jhsesa** [tus/tus-java-client#30]
I'm getting "unexpected status code (411) while creating upload" while trying to upload a file using tus client, althogugh I'm setting the header specificaly. Any thoughts?

**Comment by Acconut** [comment]
What tus server are you using? Can you show us your code responsible for performing the tus upload?

**Comment by foxware00** [comment]
I've noticed the same issue. We're using Openresty's Lua on our gateway which doesn't support chunking of requests (transfer-encoding:chunked) so renders the upload logic problematic

**Comment by Acconut** [comment]
@foxware00 That's good to know, thanks!
