### ISSUE TITLE
Content-Length missing from requests?

### ISSUE THREAD

**Issue by dmytrohridin** [tus/tus-java-client#37]
**Question**
Hello,
I am not familiar with java too much, but when we try integrate java tus client with .net backend - requests are failing with
`unexpected status code (411) while creating upload`
I'm looking through the source and seems that `Content-Length` header is missing (which required by were server that hosts .net core backend). Javascript tus client sends this header by default. And .NET HTTP client too.

**Setup details**
- Runtime environment: [Console app, Open JDK 15]
- Used tus-java-client version: [e.g. v0.4.0]
- Used tus server software: [custom]

**Comment by dmytrohridin** [comment]
Oh, content length is restricted, close

**Comment by aguarino77** [comment]
HI @dmytrohridin : what do you mean by "restricted"? We are facing exactly the same issue. How did you fix it?

**Comment by dmytrohridin** [comment]
I can not remember exacting issue, but seems it was related to this one
https://stackoverflow.com/questions/53728431/why-are-some-of-the-headers-restricted-in-httpurlconnection-after-jdk-1-6
