### ISSUE TITLE
please add example for s3 and tus 

### ISSUE THREAD

**Issue by kkangkang789** [tus/tus-java-client#39]
when i s3 and tus upload file,  i don't know if i used it wrong 
tus unable to access url, here is my code

public class TusTest {

    public static void main(String[] args) throws IOException, ProtocolException {
        AmazonS3 s3 = getMinioClient();
        GeneratePresignedUrlRequest generatePresignedUrlRequest = new GeneratePresignedUrlRequest("test1", "1313", HttpMethod.PUT);
        URL url = s3.generatePresignedUrl(generatePresignedUrlRequest);
        System.setProperty("http.strictPostRedirect", "true");

        System.out.println(url.toString());
        final TusClient tusClient = new TusClient();
        // System.out.println(s3.getUrl("test1", "1212_1.mp4"));
        // TODO 
        tusClient.setUploadCreationURL(/url);

        // 通过在内存中存储上传URL来启用可恢复的上传
        tusClient.enableResuming(new TusURLMemoryStore());
        

        File file = new File("F:\\test\\1212_" + 1 + ".mp4");
        System.out.println(file.length());
        final TusUpload upload = new TusUpload(file);

        // upload.setInputStream(new FileInputStream(file));

        TusExecutor executor = new TusExecutor() {
            @Override
            protected void makeAttempt() throws ProtocolException, IOException {
                /**
                 * 1、URL 是可以连接的，并且可以上传成功
                 * 2、但是生成的 GeneratePresignedUrlRequest httpMethod 类型为PUT , 而tus 会先设置一个请求POST
                 *
                 */
                TusUploader uploader = tusClient.resumeOrCreateUpload(upload);

                // 设置块大小5Mb 上传
                uploader.setChunkSize(5 * 1024 * 1024);
                do {
                    long totalBytes = upload.getSize();
                    long bytesUploaded = uploader.getOffset();
                    double progress = (double) bytesUploaded / totalBytes * 100;

                    System.out.printf("Upload at %06.2f%%.\n", progress);
                } while (uploader.uploadChunk() > -1);
                // 允许关闭连接
                uploader.finish();
                System.out.println("Upload finished.");
                System.out.format("Upload available at: %s", uploader.getUploadURL().toString());
            }
        };
        executor.makeAttempts();
    }

    private static AmazonS3 getMinioClient() {
        BasicAWSCredentials credentials = new BasicAWSCredentials("minioadmin", "minioadmin");
        ClientConfiguration clientConfig = new ClientConfiguration();
        AmazonS3 s3 = AmazonS3ClientBuilder.standard()
                //.withRegion(Regions.DEFAULT_REGION)
                .withCredentials(new AWSStaticCredentialsProvider(credentials))
                .withClientConfiguration(clientConfig)
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://xx.xxx.xxx.xxx:9000", " us-west-1"))
                .withPathStyleAccessEnabled(true)
                .build();

        List<Bucket> buckets = s3.listBuckets();
        for (Bucket b : buckets) {
            System.out.println(b.getName());
        }

        return s3;

    }

**Comment by Acconut** [comment]
> when i s3 and tus upload file

Sorry, but what do you mean by that? I am not able to understand these sentences. Can you explain in more detail?

**Comment by Acconut** [comment]
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)
