### ISSUE TITLE
Why can't I find it in the central warehouse.

### ISSUE THREAD

**Issue by lshz0088** [tus/tus-java-client#41]
**Question**
Why can't I find it in the central warehouse.

**Setup details**
![image](https://user-images.githubusercontent.com/27722002/105959653-24f13000-60b7-11eb-8917-7c2d4b75a23a.png)

**Comment by lshz0088** [comment]
https://mvnrepository.com/artifact/io.tus.java.client/tus-java-client

**Comment by Acconut** [comment]
Thanks for reporting, there was an error when pushing to Maven Central. Hopefully this patch will help: https://github.com/tus/tus-java-client/commit/2b0d0a3b86cf2d3828ce4320b91d76af7d28e7bd

**Comment by Acconut** [comment]
The latest version is now on Maven Central as well: https://repo1.maven.org/maven2/io/tus/java/client/tus-java-client/0.4.3/
