### ISSUE TITLE
Compiled library seems out of sync with github

### ISSUE THREAD

**Issue by cjhenck** [tus/tus-java-client#5]
The compiled client has a ProtocolException class with shouldRetry, even though master does not.

**Comment by Acconut** [comment]
Yes, this was caused by a commit which accidentally ended up in the master branch and therefore was automatically build and pushed to the registry by our automated build scripts. Is this an issue for you?

**Comment by cjhenck** [comment]
Not at all, just wasn't sure if it was known.

**Comment by Acconut** [comment]
In this case, thank you for telling us :)
