### ISSUE TITLE
Provides an interface that can replace other http clients

### ISSUE THREAD

**Issue by heowc** [tus/tus-java-client#51]
**Describe the solution you'd like**

Developers may wish to use an http client other than `HttpURLConnection` as the http client API. How about providing an interface to easily replace it?

**Comment by Acconut** [comment]
This idea has already been proposed in https://github.com/tus/tus-java-client/issues/14 and we agree that it is useful. However, no work has been done on our side so far. Feel free to leave a comment there if you want to join the discussion. I am going to close this as a duplicate.
