### ISSUE TITLE
How to set Proxy for TUSClient?

### ISSUE THREAD

**Issue by pratimsingha** [tus/tus-java-client#52]
**Question**
How to set Proxy for TUSClient?

We are using TUSClient to upload a large file to a server in chunks. We are required to go via Proxy server (with authentication).
But when I see the `createUpload` method in `TUSClient `class, I see this below line:
`HttpURLConnection connection = (HttpURLConnection) uploadCreationURL.openConnection();`

I could not see any Proxy feature that we can enable or introduce. Please suggest.

**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment: [Java Version 11]
- Used tus-java-client version: [e.g. v0.4.3]

**Comment by Acconut** [comment]
We will investigate into an easier way for setting proxies in the next major release: https://github.com/tus/tus-java-client/issues/78

**Comment by pdenooijer** [comment]
As said by @LaravZ in https://github.com/tus/tus-java-client/issues/78#issuecomment-1456353698. We could fix this pretty quickly and robust. Would you be open to review the code (provided we create a PR), merge it (after comments are resolved) and create a new release? The lack of this feature is blocking our implementation. We're behind a proxy for external connections, but don't want to use it for all request as most of them are local.
