### ISSUE TITLE
How can I log more detailed information?

### ISSUE THREAD

**Issue by lealceldeiro** [tus/tus-java-client#80]
**Question**
I'm facing this issue as well https://github.com/tus/tus-java-client/issues/66 and I'd like to be able to see detailed information about the `ProtocolException` being thrown.

Ideally, I'd like to be able to see the underlying cause of the error `400`, what was the actual response from the Cloudflare servers, etc., instead of this simple message (currently shown): `io.tus.java.client.ProtocolException: unexpected status code (400) while creating upload`

Of course, if you know of a solution for the linked issue, that'd be awesome!

Also, I've contacted already Cloudflare support -- waiting for a reply.

**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment: [Java 17, spring boot 2.7.7]
- Used tus-java-client version: v0.4.5

**Comment by lealceldeiro** [comment]
I have created a minimal reproducible example here: https://github.com/lealceldeiro/cloudflareuploader#cloudflare-uploader

**Comment by Acconut** [comment]
Where you able to fix your problem? There is no option to enable more logging in tus-java-client, unfortunately.

**Comment by lealceldeiro** [comment]
> Where you able to fix your problem? There is no option to enable more logging in tus-java-client, unfortunately.

Thanks for following up @Acconut 
I ended up debugging inside `TusClient` to find out what the problem with the upload was.
