### ISSUE TITLE
0.5.0 release missing from Maven

### ISSUE THREAD

**Issue by lwahonen** [tus/tus-java-client#87]
The documentation on the front page says

`<dependency>
  <groupId>io.tus.java.client</groupId>
  <artifactId>tus-java-client</artifactId>
  <version>0.5.0</version>
</dependency>
`

but on Maven central only 0.4.5 is available https://central.sonatype.com/artifact/io.tus.java.client/tus-java-client/0.4.5/versions

**Comment by Acconut** [comment]
Thank you. It seems the build failed: https://github.com/tus/tus-java-client/actions/runs/4468938634/jobs/7850345458 @cdr-chakotay, can you have a look?

**Comment by cdr-chakotay** [comment]
Hi @lwahonen, sorry for the late response. We forgot to update a version tag, as result Maven thought we tried to overwrite an existing package and blocked. I will release this right now!

**Comment by cdr-chakotay** [comment]
Released this successfully! Thank you for the note @lwahonen and @Acconut
