### ISSUE TITLE
Javadoc website is not updated

### ISSUE THREAD

**Issue by Acconut** [tus/tus-java-client#88]
The README links to https://tus.github.io/tus-java-client/javadoc/, but seems to be outdated. I am not sure if we have a tool to automatically update it anymore.

**Comment by cdr-chakotay** [comment]
We could also just use this service ? It just strips it from Maven:

https://javadoc.io/doc/io.tus.java.client/tus-java-client

**Comment by Acconut** [comment]
Good idea. Just did that!
