### ISSUE TITLE
Response server as JSON

### ISSUE THREAD

**Issue by jcgo810326** [tus/tus-java-client#89]
I need your clients to be able to receive a json structure, after an exception or when finishing the file upload job. It's possible??

**Comment by Acconut** [comment]
Unfortunately, there is no native feature for this right now. However, you may be able to workaround this by overwriting the `prepareConnection` method to obtain the HttpUrlConnection object. In https://github.com/tus/tus-java-client/issues/59 this is described for retrieving response headers but it may also work for the response body.

**Comment by Acconut** [comment]
Closing this in favor of https://github.com/tus/tus-java-client/issues/98
